- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker on the slave
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: run the docker image
    command: sudo docker run -it -d -P rubenito/rubendockerimage01:latest
